- .github/workflows/e2e.yaml
- cmd/config.json
- pkg/config/parser_test.go
End to end tests are failing after introduction of labels (#136). This fixes part of #248.
* Enable NodeSelector in testbed and label the node to accommodate the function.
* N/A
* N/A
> Fix end-to-end test setup

- .github/workflows/e2e.yaml
Closes #248. Adds check for e2e test failures based on output file.
* `grep`s output file for the presence of `true` values, which mean that there was a failure during invocation.
* N/A
* N/A
> Add check for failure in e2e test

- sampler/preprocess.py
- sampler/tests/preprocess_test.py
Closes #278 by filtering out functions with an average execution time of 0 ms during pre-processing.
* Remove the rows from the run_df where the average is equal to 0, use get_intersections to remove those functions from the invocations and memory dataframes.
* N/A
* N/A
> Filter out functions with 0 ms average execution time

- .gitignore
- data/traces/reference/preprocessed_150.tar.gz
- data/traces/reference/sampled_150.tar.gz
- docs/sampler.md
Add reference traces created by sampling the Azure Functions Production Trace by `sampler` part of InVitro.
> Add reference traces

- Dockerfile.trace
- Makefile
- data/traces/reference/.gitattributes
- docs/loader.md
- workloads/container/trace_func_go.yaml
- workloads/firecracker/trace_func_go.yaml
Move function container images to Github Container Registry. This will simplify updates of the images.
* Change to Makefile and Dockerfile to create images linked to Invitro repo in vhive-serverless packages.
* N/A
* Change of the function images names.
> Move function images to Github Container Registry

- .github/workflows/e2e.yaml
Update end-to-end test to use fixed test config. After update to default `config.json` the test was failing silently (e.g. [this one](https://github.com/vhive-serverless/invitro/actions/runs/6628346915/job/18005215258#step:10:11)).
> Update e2e test to use test config.json

- .github/configs/wordlist.txt
- cmd/config.json
- cmd/config_dirigent.json
- docs/configuration.md
- pkg/config/parser.go
- pkg/config/parser_test.go
- pkg/config/test_config.json
- pkg/driver/trace_driver.go
- pkg/trace/profiler.go
- pkg/trace/profiler_test.go
Signed-off-by: Leonid Kondrashov <leo.kondrashov@gmail.com>
Add option for unlimited pods in driver configuration. Now unlimited pods may be enabled by `"container_unlimited"` as `"YAMLSelector"` in `driverConfig.json`. Resolves #139.
Add new .yaml file with limits disabled, add a case in switch inside loader to pick necessary file.
N/A
N/A
> Add option for unlimited pod configuration

- .github/configs/wordlist.txt
- pkg/driver/serverless_config.go
- server/trace-func-go/aws/trace_func.go
- tools/trace_synthesizer/README.md
- tools/trace_synthesizer/__main__.py
- tools/trace_synthesizer/synthesizer.py
Chore to add MIT license to some files, improve documentation and code of trace_synthesizer tool (explicitly define code behaviour)
* N/A
* N/A
* Using mode >= 3 for trace_synthesizer tool will lead to runtime failure instead of defaulting to mode 2
> Chore: Fix Missing MIT License in Files, trace_synthesizer documentation & defining explicit behaviour 

- config/kubeadm_init.yaml
- config/metrics_server_components.yaml
- config/prometh_stack_values.yaml
While deploying Prometheus, due to the vHive k8s version up, Kubeadm caused a version collision and created an error:
```
This version of Kubeadm only supports deploying clusters with the control plane version >= 1.24.0. Current version: v1.23.0 
...
[upgrade/config] FATAL
```
Therefore, I bumped up the Kubeadm version to meet the dependency of the installed Kubernetes version.
---
Also, there was a misconfiguration in `config/kubeadm_init.yaml`:
```
localAPIEndpoint:
advertiseAddress: 10.0.1.1
```
should be under
`kind: InitConfiguration`, not `kind: ClusterConfiguration`
Also, while doing so, upgraded Api Version to `kubeadm.k8s.io/v1beta3`, as `kubeadm.k8s.io/v1beta2` is deprecated.
Now, installation is done without any errors.
> fix kubeadm config yaml and version up kubeadm

- scripts/setup/create_multinode.sh
- scripts/setup/label.sh
- scripts/setup/setup.cfg
Fix bugs introduced into the setup script during the update to the mainstream vHive version: resource requests and labels. Also, remove the GitHub token (since invitro is public, we don't need it every time).
* Move cloning repositories into `common_init` together with node stabilization (stabilization being too late in the setup was the reason for resource requests exceeding the capacity, closes #330)
* Fix master node role to control-plane, because of that, labeling wasn't working properly
* Since we don't need the SSH keys to clone the repo, remove the token completely, closes #292
* Fix labeling, so it won't create problems with redirects (remove `tmp` file, it was conflicting with collecting the logs of the script)
* N/A
* N/A
> Fix multi-node cluster creation script

- .gitignore
- pkg/driver/deployment_awslambda.go
- pkg/driver/serverless_config.go
- pkg/driver/trace_driver.go
Fixed 2 main issues with regards to **AWS Lambda deployment**:
1. Multiple `serverless.yml` to handle any number of Lambda functions
**Problem:** Unable to deploy large number of AWS Lambda functions in a single `serverless.yml` file due to limitations
**Solution:** 
1. Minimised file size of deployed serverless zip through `package.patterns` in `serverless.yml` (to avoid the [75GB Lambda Code storage limit](https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-limits.html))
2. Disabled [Lambda versioning](https://www.serverless.com/framework/docs/providers/aws/guide/functions#:~:text=Versioning%20Deployed%20Functions) through `provider.versionFunctions` in `serverless.yml`  (to minimise resources required per `.yml` file and avoid [CloudFormation 500 Resource …
> Deploying multiple `serverless.yml` to handle large number of functions

- .github/workflows/linters.yaml
**Fixed CI pipeline error for `CommitLint` due to Node versioning.**
Error Message:
```
Run commitlint --config /home/runner/work/invitro/invitro/.github/configs/commitlint.config.js --help-url 'https://stackoverflow.com/a/45974435' --from HEAD~1 --to HEAD --verbose
internal/process/esm_loader.js:7[4](https://github.com/vhive-serverless/invitro/actions/runs/8131260484/job/22220380411?pr=384#step:5:5)
internalBinding('errors').triggerUncaughtException(
^
Error [ERR_UNKNOWN_BUILTIN_MODULE]: No such built-in module: node:timers/promises
at new NodeError (internal/errors.js:322:7)
at Loader.builtinStrategy (internal/modules/esm/translators.js:289:11)
at new ModuleJob (internal/modules/esm/module_job.js:63:26)
at Loader.getModuleJob (internal/modules/esm/loader.js:2[5](https://github.com/vhive- …
```
> Fix: Updated CommitLint to Node v20

- scripts/setup/setup.cfg
vHive is experiencing a version bumping: https://github.com/vhive-serverless/vHive/pull/943
This would cause invitro inconsistency problem with vHive. So before the PR is merged, we release a v1.6.1 release and direct invitro to use it.
Change the vhive branch in setup script from `main` to `1.6.1`
N/A
N/A
> Fix vhive version to 1.6.1

- pkg/driver/deployment_awslambda.go
- pkg/driver/http_client.go
- pkg/driver/serverless_config.go
**Fixed AWS API Gateway timeout limit for AWS Lambda deployment, by replacing API Gateway with Lambda function URL to generate invocation URL**
**Problem:** Previous deployment with API Gateway (with differing page paths for each Lambda function) can only handle invocations within 29 seconds due to gateway timeout. However, actual traces involve invocations longer than 29s. Although our current code filters for invocations under 1 minute, it is not sufficient to address the problem.
**Included minor fixes to improve the logging description of errors.
**Solution:** Utilise AWS' Lambda function URL feature to increase the maximum invocation duration to 15 minutes (same as Lambda execution timeout limit). 
Therefore, program can now handle any `requestedDuration` within 15 minutes and the …
> Fix: Use Lambda URL to bypass Gateway timeout limit

- .github/configs/wordlist.txt
- cmd/config.json
- cmd/config_dirigent.json
- docs/configuration.md
- pkg/config/parser.go
- pkg/config/test_config.json
- pkg/driver/trace_driver.go
- pkg/driver/trace_driver_test.go
In current implementation, single execution of ```go run cmd/loader.go --config cmd/config.json``` would create an ```individualFunctionDriver``` per function and invoke individual functions with a set frequency. 
The new implementation would create a new ```functionsDriver``` which invoke all the functions sequentially, following the invocation frequency of the first function.
* Added a new parameter ```DAGMode``` in ```cmd/config.json``` to toggle DAGMode.
* When DAGMode = true, ```functionsDriver()``` in the full list of provided functions and invokes them sequentially in a loop. 
* Added a new ```Node``` structure to hold function pointers and pointer to the next Node
* Edited parameter in ```invokeGRPC()``` to reflect invocation stats for each function.
* (N/A)
* (N/A)
*Simply …
> "Creating a simple DAG Driver for Knative"

- pkg/driver/trace_driver_test.go
The fix is to address the Data Race Issue caused by the commit 31c635c19204ee7cd4aa18867a6d1c3d11850052 .
* The Issue is caused by multiple goroutines simultaneously calling ```StartGRPCServer()```, which interacts with global variables. Since the test involves sequentially invoking a single function multiple times, ```StartGRPCServer()``` should be called once only. 
* Moved ```StartGRPCServer()``` out of for loop. 
* NA
* NA
> Fix: Resolved Data Race Issue caused by DAGInvocation Test

- .github/configs/wordlist.txt
- Dockerfile.trace.aws
- docs/loader.md
- pkg/common/constants.go
- pkg/driver/deployment_awslambda.go
- pkg/driver/serverless_config.go
- scripts/setup/install_aws_dependencies.sh
Due to the following reasons, the zip deployment approach for AWS Lambda is no longer supported by our project. Instead, the image deployment via ECR will be adopted:
1. AWS deprecation of `go1.x` runtime (as highlighted in an earlier [PR](https://github.com/vhive-serverless/invitro/pull/398))
2. Limitations of zip deployment (primarily the maximum number of functions deployable due to [75GB code storage limit](https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-limits.html))
3. Alignment to other existing image deployments
Refactored code to handle errors more gracefully.
<b>New Feature: Image Deployment</b>
* Pulls the default image (built using `./Dockerfile.trace.aws` and `./server/trace-func-go/aws/trace_func.go`) from our [public GHCR …
> Feature: Changed Support from Zip to Image Deployment on AWS via ECR

- .github/workflows/e2e_aws.yaml
- pkg/config/test_config_aws.json
Includes an end-to-end CI/CD workflow on GitHub Actions to test for AWS Lambda deployment.
This workflow is triggered only upon `push` to the `main` branch, or manually from the `Actions` tab.
- As workflow is triggered only upon commit to `main` branch, PRs will not capture any failure in AWS end-to-end deployments before merging
- Currently, workflow trigger is disabled on `pull_request` as secrets are not accessible from forked repository
- As the code for AWS deployment is rather localised, the above workflow trigger setting will minimise any disruptions to developers
- If required, developers can manually trigger the workflow under the `Actions` tab
- The required secrets (AWS credentials) will be verified prior to running the workflow
- If missing / not set, workflow will fail as …
> Feature: Added End-to-End Integration Test for Cloud Deployment (AWS)

- .github/workflows/e2e.yaml
- config/prometh_values_kn.yaml
- scripts/setup/create_multinode.sh
- scripts/setup/create_singlenode_container.sh
- scripts/setup/rewrite_yaml_files.sh
- scripts/setup/setup.cfg
- workloads/container/trace_func_go.yaml
For multi-node clusters, we label nodes with three values for loader-nodetype: master, monitoring, and worker. In the single-node case, we cannot label the node with all three of them, which leads to issues with placement. To address this, we propose to use the node affinity option instead of node selectors. This should allow us to choose one of the labels.
1. Create a new label: `singlenode`, to identify single-node instances.
2. Update the node selectors in the following three places to use node affinity with the old label and the new `singlenode` label:
- Knative services (master)
- Prometheus (monitoring)
- Worker pods (worker)
N/A
N/A
> solve the label issue of singlenode through affinity

- scripts/setup/create_multinode.sh
Add function to the create_multinode setup script to generate and distribute the SSH key to all other nodes.
* Generate an RSA key pair for the loader node
* Copy the RSA public key to the local loader node
* Distribute the RSA public key from the loader node to all other nodes
* N/A
* N/A
> Distribute loader SSH key in create_multinode setup

- scripts/setup/create_multinode.sh
- scripts/setup/create_singlenode_container.sh
- scripts/setup/install_aws_dependencies.sh
- scripts/setup/setup.cfg
Adds a separate variable for `VHIVE_REPO` and `LOADER_REPO` in `./scripts/setup/setup.cfg` to be able to use private repos in setup script (fixes vhive-serverless/invitro#538).
* Briefly outline the overall technical solution. If necessary, identify talking points where the reviewer's attention should be drawn to.
In scripts under setup directory, next to every `VHIVE_BRANCH` and `LOADER_BRANCH`, repository urls are replaced with a proper variable which has already defined in `setup.cfg`. 
* N/A
* N/A
> Add VHIVE_REPO and LOADER_REPO to setup script config

- cmd/loader.go
Fix default values for loader.go configurations. Right now, you need to specify it if you run it from the repo's root directory as it is specified in [docs](https://github.com/vhive-serverless/invitro/blob/main/docs/loader.md#single-execution). Otherwise, it fails because the loader can't find failure.json.
* Change values to point to files in `cmd` directory
* N/A
* Update default values used in loader
> Fix default argument values

- pkg/driver/failure/triggers.go
In previous version, the default failure config was triggering failure even when FailureEnabled was set to false
* Check for the enabled flag before triggering the failure
* N/A
* N/A
> Correctly enable failure generation

- cmd/loader.go
- docs/loader.md
- pkg/common/constants.go
- pkg/common/validators.go
Adds a dry run flag to the loader, enabling users to execute the loader without generating trace loads or running experiments. Also adds a simple validation for cpu limit field in loader config.
* Add a dryRun flag to the loader which accepts a boolean value.
* Modifies the execution flow to exit early by checking the dryRun flag just before calling RunExperiment via the experiment driver in the runTraceMode function
* Add a simple validation to ensure provided cpu limit in loader config is valid
* N/A
* N/A
> add loader dry run

- .github/workflows/e2e.yaml
- .github/workflows/e2e_aws.yaml
- cmd/config_dirigent_dandelion_rps.json
- cmd/config_dirigent_rps.json
- cmd/config_knative_rps.json
- cmd/loader.go
- docs/configuration.md
- pkg/driver/clients/invoker.go
- pkg/driver/deployment/deployer.go
- pkg/driver/failure/triggers.go
Fixes #536. Extracts the RPS option from Platform. 
* Create a special value for the trace selector (`RPS`). This would work because we can use either trace path or RPS mode, but not both.
* N/A
* Changes the Platform and TracePath configuration parameters.
> Extract RPS knob from Platform setting

- .github/workflows/unit-tests.yaml
- go.mod
- go.sum
- pkg/config/parser.go
- pkg/driver/clients/grpc_client.go
- pkg/driver/clients/grpc_client_test.go
- pkg/driver/clients/invoker.go
- pkg/driver/clients/vhivemetadata.go
A small summary of the requirements (in one/two sentences).
* Briefly outline the overall technical solution. If necessary, identify talking points where the reviewer's attention should be drawn to.
* 
* 
> Tweaked invoker and added tests

- config/prometh_values_kn.yaml
Set enableAdminAPI to true to enable administrative HTTP API for Prometheus. Without this administrative endpoints like `/-/snapshot` will not be available, preventing you from generating a snapshot of the TSDB data. Other endpoints, such as `/-/reload` and `/-/quit`, will also be inaccessible.
- set `enableAdminAPI` to` true` in `config/prometh_values_kn.yaml` under `prometheusSpec`
* N/A
* N/A
> Enable Admin API for prometheus

- cmd/loader.go
- pkg/config/configuration.go
- pkg/generator/rps.go
Removing redundant fields that added consistency problems.
> YAMLSelector bugfix for Knative RPS

- scripts/setup/create_multinode.sh
- scripts/setup/setup.cfg
-> fixed
- Bumped vHive version to v1.8. We fixed the network issue created when migrating to Ubuntu 24.
- fixed chrony so it would not spit out errors since they are already running in the background
-> not fixed
- installing pip requirements does not work, can remove if not required, since it is not essential when running loadgen (but currently breaking all the CIs)
> fix invitro script and config to work with ubuntu 24 profile

- pkg/driver/deployment/knative.sh
Summary
Removing the --concurrency-target flag from the knative.sh script as it conflicts with the containerConcurrency setting defined in trace_func_go.yaml. Since containerConcurrency specifies a hard limit, adding a soft limit via --concurrency-target=1 can lead to unexpected behaviour when containerConcurrency > 1.
Details 
Hard Limit: Configured via containerConcurrency, strictly enforces the maximum concurrent requests per container.
Soft Limit: Configured via --concurrency-target or autoscaling.knative.dev/target, is a guideline that can be exceeded.
When both limits exist, the smaller value takes precedence. Removing the redundant soft limit avoids conflicts and ensures predictable scaling behaviour.
More information provided in Knative documentation: …
> Remove --concurrency-target Flag from knative.sh
